ALTER TABLE topics ADD COLUMN kind TEXT NOT NULL DEFAULT 'topic';
ALTER TABLE topics ADD COLUMN parent_id TEXT NOT NULL DEFAULT '';
ALTER TABLE topics ADD COLUMN parent_title TEXT NOT NULL DEFAULT '';
ALTER TABLE topics ADD COLUMN catalog_path TEXT NOT NULL DEFAULT '';
ALTER TABLE topics ADD COLUMN trainable INTEGER NOT NULL DEFAULT 1;

